feat: Initialize base project.
ExxiDauS/T-Rex-Flowchart pull request #1
Opened 2024-03-01 16:28 UTC by ExxiDauS

2024-03-01 16:41 UTC, pubethSri reviewed
**Cool.** to add, I think in the constructor of flowchart we can create *Start* and add it at the first index of *flowchart* order (ArrayList) and change the attribute name to match naming rule *Order* -> *order*

2024-03-01 16:43 UTC, KuhnphOn requested changes
- Change getCode Method to convertToCode for less confusion.
- Encapsulate attribute in Flowchart.java

2024-03-01 16:51 UTC, ExxiDauS commented
> **Cool.** to add, I think in the constructor of flowchart we can create _Start_ and add it at the first index of _flowchart_ order (ArrayList) and change the attribute name to match naming rule _Order_ -> _order_

Add the _Start_ . Does that mean I'll have to create a var?

2024-03-01 17:11 UTC, ExxiDauS commented
- [ x ] Initialize start at Flowchart constructor.
- [ x ] Change the _Order_ attribute to correct the naming rule.
- [ x ] Change the name of the method to less complicated.
- [ x ] Encapsulate **Flowchart** fields.

2024-03-01 17:13 UTC, KuhnphOn commented on Main_project/src/Flowchart.java
Nice1

2024-03-01 17:14 UTC, KuhnphOn reviewed
I'm good with these changes. //Leave the comment here for others to review changes.

2024-03-01 20:57 UTC, pubethSri approved these changes
### **Very Cool.** Pretty sure it's ok to merge now.
![sonic-boom-knuckles](https://github.com/ExxiDauS/T-Rex-Flowchart/assets/138897364/20ec2e8f-7ded-4774-b6ac-1096896816f7)

2024-03-02 10:15 UTC, KuhnphOn approved these changes

2024-03-02 10:16 UTC, merged